version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout

      - run:
          name: Check flutter status
          command: flutter doctor

      - run:
          name: Install JUnitReport
          command: pub global activate junitreport

      - run:
          name: Create directory structure for test-results
          command: mkdir --parents /tmp/test-results/flutter

      - run:
          name: Get Flutter packages to avoid stdout in JSON
          command: flutter packages get

      - run:
          name: Run Flutter tests.
          command: flutter test --machine > /tmp/test-results/flutter/TEST-report.json

      - run:
          name: Convert Flutter tests to JUnit
          command: $HOME/.pub-cache/bin/tojunit --input /tmp/test-results/flutter/TEST-report.json --output /tmp/test-results/flutter/junit.xml
          when: always

      - run:
          name: Build APK
          command: flutter -v build apk

      - run:
          name: Rename Binary
          command: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/spikey.apk

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: build/app/outputs/apk/release/spikey.apk
          destination: spikey.apk

      - persist_to_workspace:
          root: .
          paths:
            - build/app/outputs/apk/release/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=1.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate ${CIRCLE_BRANCH} spikey.apk

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
